import sqlite3
import json
import os

DB_NAME = "legal_faqs.db"

def init_db():
    """Initialize the SQLite database and populate it from faqs.json."""
    if os.path.exists(DB_NAME):
        return

    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    
    c.execute('''CREATE TABLE IF NOT EXISTS faqs (
                    id INTEGER PRIMARY KEY,
                    intent TEXT,
                    question_hi TEXT,
                    question_ta TEXT,
                    question_en TEXT,
                    answer_hi TEXT,
                    answer_ta TEXT,
                    answer_en TEXT,
                    citation TEXT,
                    case_study TEXT
                )''')
    
    try:
        with open("faqs.json", "r", encoding="utf-8") as f:
            data = json.load(f)
            for item in data:
                c.execute('''INSERT INTO faqs (intent, question_hi, question_ta, question_en, 
                                             answer_hi, answer_ta, answer_en, citation, case_study)
                             VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)''', 
                          (item['intent'], item['question_hi'], item['question_ta'], item['question_en'],
                           item['answer_hi'], item['answer_ta'], item['answer_en'], item['citation'], item.get('case_study', '')))
        conn.commit()
    except Exception as e:
        print(f"Error loading initial data: {e}")
    finally:
        conn.close()

def get_answer_by_intent(intent, lang_code='en'):
    """Retrieve answer based on intent and language."""
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    
    c.execute("SELECT * FROM faqs WHERE intent=?", (intent,))
    result = c.fetchone()
    conn.close()
    
    if result:
        # result index mapping: 
        # 0: id, 1: intent, 2: hi, 3: ta, 4: en (ques), 5: hi, 6: ta, 7: en (ans), 8: citation, 9: case_study
        
        case_study = result[9]
        if lang_code == 'hi':
            return result[5], result[8], case_study
        elif lang_code == 'ta':
            return result[6], result[8], case_study
        else:
            return result[7], result[8], case_study
    return None, None, None

def search_db(query, lang_code=None):
    """Improved keyword search across ALL languages."""
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    
    # Select all question columns
    c.execute("SELECT intent, question_en, question_hi, question_ta FROM faqs")
    rows = c.fetchall()
    conn.close()

    query_tokens = [t for t in query.lower().split() if len(t) > 2] # Ignore very short words like 'i', 'in', 'is'
    matches = []

    for row in rows:
        intent = row[0]
        # Check against all 3 languages (indices 1, 2, 3)
        questions = [q for q in row[1:] if q]
        
        best_match_count = 0
        
        for question in questions:
            q_tokens = question.lower().split()
            match_count = 0
            
            for qt in query_tokens:
                if qt in q_tokens: # Exact word match
                    match_count += 1
            
            if match_count > best_match_count:
                best_match_count = match_count
        
        if best_match_count > 0:
            # Append match with the highest score found in any language
            matches.append((intent, best_match_count))

    # Sort by number of matches desc
    matches.sort(key=lambda x: x[1], reverse=True)
    
    # Return formatted list (intent, score) -> App expects list of tuples, intent at 0
    return [(m[0], m[1]) for m in matches]

def add_to_db(intent, question, answer, lang_code, citation="Generated by AI"):
    """Adds a new FAQ entry or updates existing one."""
    conn = sqlite3.connect(DB_NAME)
    c = conn.cursor()
    
    # Check if intent exists
    c.execute("SELECT id FROM faqs WHERE intent=?", (intent,))
    existing = c.fetchone()
    
    if existing:
        # Update existing
        q_col = f"question_{lang_code}"
        a_col = f"answer_{lang_code}"
        c.execute(f"UPDATE faqs SET {q_col} = ?, {a_col} = ?, citation = ? WHERE intent = ?", 
                  (question, answer, citation, intent))
    else:
        # Insert new
        q_col = f"question_{lang_code}"
        a_col = f"answer_{lang_code}"
        c.execute(f"INSERT INTO faqs (intent, {q_col}, {a_col}, citation) VALUES (?, ?, ?, ?)", 
                  (intent, question, answer, citation))
    
    conn.commit()
    conn.close()

    # --- Also update faqs.json so NLP Engine can see it ---
    try:
        with open("faqs.json", "r", encoding="utf-8") as f:
            faqs = json.load(f)
    except:
        faqs = []

    found = False
    for item in faqs:
        if item['intent'] == intent:
            item[f"question_{lang_code}"] = question
            item[f"answer_{lang_code}"] = answer
            item["citation"] = citation
            found = True
            break
            
    if not found:
        new_item = {
            "intent": intent,
            "question_en": "",
            "question_hi": "",
            "question_ta": "",
            "answer_en": "",
            "answer_hi": "",
            "answer_ta": "",
            "citation": citation,
            "case_study": ""
        }
        new_item[f"question_{lang_code}"] = question
        new_item[f"answer_{lang_code}"] = answer
        faqs.append(new_item)

    with open("faqs.json", "w", encoding="utf-8") as f:
        json.dump(faqs, f, indent=4, ensure_ascii=False)

if __name__ == "__main__":
    init_db()
    print("Database initialized.")
